### PR TITLE
Support for modpacks

### LINKED ISSUE #5: Add support for CurseForge and Modrinth modpacks
The [CurseForge API](https://docs.curseforge.com) doesn't mention modpacks anywhere so we'll have to implement the modpack format, which is just a json file I believe. This might be why GDLauncher/MultiMC doesn't support modpacks, they aren't in the API

### PR DESCRIPTION
**Pull request by theRookieCoder**
Will fix #5

### CODE REVIEW

**Comment by theRookieCoder** [comment]
Currently, the problem is that upgrading is very unstable. I've never been able consistently download, it alwats gets stuck downloading about 5 mods.

**Comment by theRookieCoder** [comment]
Oh and there are no integrations tests for the modpack subcommands yet

**Comment by theRookieCoder** [comment]
Oh yeah [`Semaphore`](https://docs.rs/tokio/latest/tokio/sync/struct.Semaphore.html) to the rescue. Downloads are much more stable with it. I guess 200 concurrent network requests and file writes is a bad idea

**Comment by theRookieCoder** [comment]
With downloads fixed, we can finally move on to Modrinth pack support. Amazing that alpha modpack support was _just_ released ysterday

**Comment by theRookieCoder** [comment]
Downloading of mods in modpacks is stable and basically finished. After implenting overrides, v4 will be released

**Comment by theRookieCoder** [comment]
Yes the config has had breaking changes. Add the following to your config to get it to work
```json
"active_modpack": 0,
"modpacks": [],
```

**Comment by theRookieCoder** [comment]
Oh yes I remember now optional mods need to be implemented too

**Comment by KyleUltimate** [comment]
> Yes the config has had breaking changes. Add the following to your config to get it to work
> 
> ```json
> "active_modpack": 0,
> "modpacks": [],
> ```

Yep it now works!

**Comment by theRookieCoder** [comment]
Everything pretty much works now. The only problem is that modpacks made using packwiz will fail to be unzipped beacause packwiz produces corrupted zip files

**Comment by theRookieCoder** [comment]
Fixed it in Libium! Will be doing a code review, then I'll release it tomorrow!

**Comment by KyleUltimate** [comment]
Maybe a `jq` inplace?
`cat ~/.config/ferium/config.json | jq '.active_modpack += 0' | tee ~/.config/ferium/config.json`
`cat ~/.config/ferium/config.json | jq '.modpacks += []' | tee ~/.config/ferium/config.json`
(idk how to combine them)

**Comment by theRookieCoder** [comment]
I'm not sure if most people would have even heard of `jq`, I think a simple 'copy this and paste at the top of the file' is enough.

**Pull request merged**
