### PR TITLE
Support for sha256 uploads

### PR DESCRIPTION
**Pull request by KyleUltimate**
Supports for Scoop.

### CODE REVIEW

**Comment by theRookieCoder** [comment]
Does `sha256sum` exist? Isn't it `shasum -a 256`, or is this an alias on linux only?

**Comment by theRookieCoder** [comment]
Also the file should be added to `./out` because that's where files are uploaded from

**Comment by KyleUltimate** [comment]
`sha256sum` does exist on linux. and fixed it to added to `out`!

**Comment by theRookieCoder** [comment]
Great! We can test this on `3.28.1` soon

**Comment by KyleUltimate** [comment]
yeah, once they approve the package.
It will be updated automatically every week

**Comment by theRookieCoder** [comment]
Oh the file should be taken from the out directory too

**Pull request merged**
