### PR TITLE
Update AUR packages in the build and release workflow

### PR DESCRIPTION
**Pull request by KyleUltimate**
This should automatically update the AUR via actions.
you have to set the ssh secret in order to let it work.
I have a question though, is github.ref_name the version number?
This is the correct branch :rofl:

### CODE REVIEW

**Comment by theRookieCoder** [comment]
`github.ref_name` returns the tag name (e.g. `v1.22.0`) because it activates on tag pushes

**Comment by theRookieCoder** [comment]
Also the authentication is really messy, does AUR only support SSH? Actually GPG wouldn't work in this case would it?

**Comment by KyleUltimate** [comment]
> `github.ref_name` returns the tag name (e.g. `v1.22.0`) because it activates on tag pushes

yep, then this pull request would be correct.(It should be, haven't tried running it completely cause it's hard to test this without changing the tag). But how would I give you my secret?

**Comment by theRookieCoder** [comment]
You can add me (`theRookieCoder`) as a maintainer on the AUR, I'll add my SSH secret (that's how it works right?)

**Comment by KyleUltimate** [comment]
This should work perfectly!
It basically did what I do but in a cleaner manner!

**Comment by theRookieCoder** [comment]
Oh and you can split the project into `ferium-bin` and `ferium-gui-bin` after I get the release working. I can't get the tests to run because I keep getting rate limited, now I have to add authentication just to get the tests to run :(

**Comment by KyleUltimate** [comment]
> You can add me (`theRookieCoder`) as a maintainer on the AUR package, I'll add my SSH secret (that's how it works right?)

Well... It's a little bit more complicated than that.
1. You first have to sign up for the AUR(https://aur.archlinux.org/register)
2. https://wiki.archlinux.org/title/AUR_submission_guidelines#Authentication
3. And it seems like adding you as the maintainer in the PKGBUILD would work?
image
But idk should I use your name(`theRookieCoder`), or your email

**Comment by theRookieCoder** [comment]
I've already registered with the username I mentioned previously, and I think as far as AUR is concerned username and email are the same. But the format seems to be name and email so just like the `Cargo.toml`, you should put `Ilesh Thiada <ileshkt@gmail.com>` to add me as a maintainer I guess.

**Comment by theRookieCoder** [comment]
The action seems to remove the 'v' from the tag name too which is perfect, so `v3.22.0` becomes `3.22.0`

**Comment by theRookieCoder** [comment]
I don't get it? The version tags have a v in front of them, but that should be removed and the aur action does this automatically

**Comment by KyleUltimate** [comment]
Oh wait yeah, you're right. Now I think it's just time for waiting. When you're rate limit get raised

**Comment by theRookieCoder** [comment]
Unfortunately I'm gonna have to test this stuff tomorrow. I managed to get the action to make a release, so you can update the package information accordingly. It has a no gui version for linux now too so you can remove the GTK dependency from `ferium-bin`, and create `ferium-gui-bin`.

**Comment by KyleUltimate** [comment]
For the non gui, namcap says it needs gcc-libs. 
image
This is normal right?

**Comment by theRookieCoder** [comment]
I think this is typical of Rust binaries built for `gnu` targets. In fact even Cargo has [a similar issue](https://github.com/rust-lang/rustup/issues/2213) on distros that use `musl` such as alpine because it assumes the distro has gcclibs by default.

**Comment by theRookieCoder** [comment]
Oh and how would I test this without messing up the AUR package?

**Pull request merged**
